;;; spaceline-all-the-icons-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from spaceline-all-the-icons.el

(autoload 'spaceline-all-the-icons-theme "spaceline-all-the-icons" "\
Install the `spaceline-ml-all-the-icons'.
Add ADDITIONAL-SEGMENTS to the end of the theme.

(fn &rest ADDITIONAL-SEGMENTS)" t)
(register-definition-prefixes "spaceline-all-the-icons" '("spaceline-all-the-icons-"))


;;; Generated autoloads from spaceline-all-the-icons-segments.el

(register-definition-prefixes "spaceline-all-the-icons-segments" '("define-spaceline-all-the-icons--" "dirs" "files" "installed" "new" "spaceline-all-the-icons-" "upgrade"))


;;; Generated autoloads from spaceline-all-the-icons-separators.el

(register-definition-prefixes "spaceline-all-the-icons-separators" '("define-spaceline-all-the-icons--separator" "left-" "minor-mode-" "paradox-" "right-" "spaceline-all-the-icons-separator"))

;;; End of scraped data

(provide 'spaceline-all-the-icons-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; spaceline-all-the-icons-autoloads.el ends here
